<?php

namespace App\Controller\Apibundle;
use App\Utility\Socket;
use App\Utility\Tools;
use Cake\Auth\DefaultPasswordHasher;
use Cake\Event\Event;
use Firebase\JWT\JWT;
use RestApi\Controller\ApiController;


class InitController extends ApiController
{

    public function initialize()
    {
        parent::initialize();
        $this->apiResponse['flash'] = null;

    }

    public function beforeFilter(Event $event)
    {


        parent::beforeFilter($event); // TODO: Change the autogenerated stub

        if (isset($_SERVER['HTTP_ORIGIN'])) {
            header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
            header('Access-Control-Allow-Credentials: true');
            header('Access-Control-Max-Age: 1000');    // cache for 1 day
        }

        // Access-Control headers are received during OPTIONS requests
        if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
            if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']))
                header("Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS");

            if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
                header("Access-Control-Allow-Headers: {$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");

        }

        if ($this->request->is('options')) {
            return $this->response;
        }

        $this->_performTokenValidation($event);

    }


    protected function _performTokenValidation(Event $event)
    {
        $request = $event->getSubject()->request;

        if (!empty($request->params['allowWithoutToken']) && $request->params['allowWithoutToken']) {
            return true;
        }

        $token = '';

        $header = $request->getHeader('Authorization');

        if (!empty($header)) {

            $parts = explode(' ', $header[0]);

            if (count($parts) < 2 || empty($parts[0]) || !preg_match('/^Bearer$/i', $parts[0])) {
                return $this->response->withStatus(401, 'InvalidTokenFormat');
            }

            $token = $parts[1];
        } elseif (!empty($this->request->getQuery('token'))) {
            $token = $this->request->getQuery('token');
        } elseif (!empty($request->data['token'])) {
            $token = $request->data['token'];
        } else {
            return $this->response->withStatus(401, 'MissingToken');
        }

        try {
            $payload = JWT::decode($token, TOKEN_CYPHER_KEY, [TOKEN_ALGORYTHM]);
        } catch (\Exception $e) {
//            if expired => try renew
            if ($e->getCode() == 0) {
                $this->renewToken($token);
            }


            return $this->response->withStatus(401, 'InvalidToken');

        }

        if (empty($payload)) {
            return $this->response->withStatus(401, 'InvalidToken');
        }

        return true;
    }


    private function renewToken($token)
    {
        JWT::$leeway = 720000;
        $payload = Tools::decodeJwt($token);
        $response = $this->checkLogin($payload->user->cellphone_code, $payload->user->cellphone);

        $this->apiResponse['jwt'] = $response['jwt'];
        $this->httpStatusCode = $response['httpStatusCode'];
    }


    protected function checkLogin($cellphone_code, $cellphone, $password = null)
    {
        $return = [
            'httpStatusCode' => 400,
            'flash' => null,
            'payload' => null,
            'jwt' => null,
            'user' => null,
        ];

        $this->loadModel('Users');
        $user = $this->Users->find()
            ->where(['Users.cellphone_code' => $cellphone_code, 'Users.cellphone' => $cellphone])
            ->first();

        if ($user) :
//            if ($password) {
//                $verify = (new DefaultPasswordHasher())->check($password, $user->password);
//            } else {
//                $verify = true;
//            }
            $verify = true;
            if ($verify) :
                $payload = Tools::setPayload($user);
                $return['httpStatusCode'] = 200;
                $return['jwt'] = Tools::encodeJwt($payload);
                $return['payload'] = $payload;
                $return['user'] = $user;
            else :
                $return['httpStatusCode'] = 400;
                $return['flash'] = 'Mot de passe incorrect';
            endif;
        else:
            $return['httpStatusCode'] = 400;
            $return['flash'] = 'Téléphone incorrect';
        endif;

        return $return;
    }
}
