<?php

namespace App\Controller\Publicbundle;

use App\Controller\AppController;
use Cake\Event\Event;


class InitController extends AppController
{

    public function initialize()
    {
        parent::initialize();

    }
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }


}
